// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interfaces.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetAllTree mocks base method.
func (m *MockRepositoryInterface) GetAllTree(ctx context.Context, input UuidInput) ([]TreeModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTree", ctx, input)
	ret0, _ := ret[0].([]TreeModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTree indicates an expected call of GetAllTree.
func (mr *MockRepositoryInterfaceMockRecorder) GetAllTree(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTree", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAllTree), ctx, input)
}

// GetTestById mocks base method.
func (m *MockRepositoryInterface) GetTestById(ctx context.Context, input GetTestByIdInput) (GetTestByIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestById", ctx, input)
	ret0, _ := ret[0].(GetTestByIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestById indicates an expected call of GetTestById.
func (mr *MockRepositoryInterfaceMockRecorder) GetTestById(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTestById), ctx, input)
}

// InsertEstate mocks base method.
func (m *MockRepositoryInterface) InsertEstate(ctx context.Context, input CreateEstateInput) (UuidOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEstate", ctx, input)
	ret0, _ := ret[0].(UuidOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEstate indicates an expected call of InsertEstate.
func (mr *MockRepositoryInterfaceMockRecorder) InsertEstate(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEstate", reflect.TypeOf((*MockRepositoryInterface)(nil).InsertEstate), ctx, input)
}

// InsertTree mocks base method.
func (m *MockRepositoryInterface) InsertTree(ctx context.Context, input CreateTreeInput) (UuidOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTree", ctx, input)
	ret0, _ := ret[0].(UuidOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTree indicates an expected call of InsertTree.
func (mr *MockRepositoryInterfaceMockRecorder) InsertTree(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTree", reflect.TypeOf((*MockRepositoryInterface)(nil).InsertTree), ctx, input)
}
